// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: grpc/proto.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AquaWallah_SendRequest_FullMethodName = "/AquaWallah/SendRequest"
	AquaWallah_SendReply_FullMethodName   = "/AquaWallah/SendReply"
)

// AquaWallahClient is the client API for AquaWallah service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AquaWallahClient interface {
	SendRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Empty, error)
	SendReply(ctx context.Context, in *Reply, opts ...grpc.CallOption) (*Empty, error)
}

type aquaWallahClient struct {
	cc grpc.ClientConnInterface
}

func NewAquaWallahClient(cc grpc.ClientConnInterface) AquaWallahClient {
	return &aquaWallahClient{cc}
}

func (c *aquaWallahClient) SendRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AquaWallah_SendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aquaWallahClient) SendReply(ctx context.Context, in *Reply, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AquaWallah_SendReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AquaWallahServer is the server API for AquaWallah service.
// All implementations must embed UnimplementedAquaWallahServer
// for forward compatibility.
type AquaWallahServer interface {
	SendRequest(context.Context, *Request) (*Empty, error)
	SendReply(context.Context, *Reply) (*Empty, error)
	mustEmbedUnimplementedAquaWallahServer()
}

// UnimplementedAquaWallahServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAquaWallahServer struct{}

func (UnimplementedAquaWallahServer) SendRequest(context.Context, *Request) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRequest not implemented")
}
func (UnimplementedAquaWallahServer) SendReply(context.Context, *Reply) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendReply not implemented")
}
func (UnimplementedAquaWallahServer) mustEmbedUnimplementedAquaWallahServer() {}
func (UnimplementedAquaWallahServer) testEmbeddedByValue()                    {}

// UnsafeAquaWallahServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AquaWallahServer will
// result in compilation errors.
type UnsafeAquaWallahServer interface {
	mustEmbedUnimplementedAquaWallahServer()
}

func RegisterAquaWallahServer(s grpc.ServiceRegistrar, srv AquaWallahServer) {
	// If the following call pancis, it indicates UnimplementedAquaWallahServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AquaWallah_ServiceDesc, srv)
}

func _AquaWallah_SendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AquaWallahServer).SendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AquaWallah_SendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AquaWallahServer).SendRequest(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _AquaWallah_SendReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Reply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AquaWallahServer).SendReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AquaWallah_SendReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AquaWallahServer).SendReply(ctx, req.(*Reply))
	}
	return interceptor(ctx, in, info, handler)
}

// AquaWallah_ServiceDesc is the grpc.ServiceDesc for AquaWallah service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AquaWallah_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AquaWallah",
	HandlerType: (*AquaWallahServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendRequest",
			Handler:    _AquaWallah_SendRequest_Handler,
		},
		{
			MethodName: "SendReply",
			Handler:    _AquaWallah_SendReply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto.proto",
}
